# --- deploy_auditsystem.yml ---
# 這是主要的 Ansible Playbook，它會依序執行所有 roles 來完成部署。

- name: Deploy AuditSystem to VM
  hosts: auditsystem_vms
  become: yes
  gather_facts: yes
  vars_files:
    - inventories/production/group_vars/all/main.yml
    - inventories/production/group_vars/all/vault.yml

  roles:
    - role: common
    - role: nacos
    - role: backend
    - role: frontend
    - role: nginx

  post_tasks:
    - name: Start all services after deployment
      ansible.builtin.command:
        cmd: ./manage-services.sh start
        chdir: "{{ scripts_dest_path }}"
      register: start_services_result
      changed_when: "'starting' in start_services_result.stdout | lower"
      tags:
        - start_services