# auditsystem-ansible/roles/java/tasks/main.yml
---
- name: "Install OpenJDK 11"
  ansible.builtin.apt:
    name:
      - openjdk-11-jdk
      - openjdk-11-jre
    state: present

- name: "Set Java 11 as the default alternative"
  ansible.builtin.alternatives:
    name: "{{ item }}"
    path: "/usr/lib/jvm/java-11-openjdk-amd64/bin/{{ item }}"
  loop:
    - java
    - javac

- name: "Ensure JAVA_HOME is set in /etc/environment"
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^export JAVA_HOME="
    line: "export JAVA_HOME={{ java_home_path }}"
    state: present
    create: yes