# --- inventories/production/group_vars/all/main.yml ---
# 存放所有主機群組都會用到的通用變數。

# 遠端 SSH 使用者
remote_user: azureuser

# 專案在遠端主機上的根目錄
project_root_dir: /opt/auditsystem

# Ansible 控制節點上，部署腳本來源目錄的相對路徑
scripts_src_path: ../../files/AuditSystemVM

# 部署腳本將被複製到遠端主機上的目標路徑
scripts_dest_path: "/home/{{ remote_user }}/AuditSystemVM_Deployment"

# 應用程式相關設定
nacos_user: nacos
mysql_user: auditsystem
db_name: bytefinger_toutuo
app_admin_user: admin