FROM 10.0.1.135:8080/base-images/openjdk:11-jre
ADD bytefinger-modules/bytefinger-biz/target/bytefinger-biz.jar app.jar
EXPOSE 8203
ENTRYPOINT ["java","-jar","-Dfile.encoding=UTF-8","-Duser.timezone=GMT+08","-Dspring.profiles.active=uat","-Xms256m","-Xmx6144m","/app.jar"]

