server:
  port: 8200
spring:
  application:
    name: bytefinger-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: 
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace:
        group: bytefinger-audit-local
        file-extension: yml
    gateway:
      routes:
        - id: bytefinger-auth
          uri: lb://bytefinger-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: bytefinger-system
          uri: lb://bytefinger-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: bytefinger-biz
          uri: lb://bytefinger-biz
          predicates:
            - Path=/biz/**
          filters:
            - StripPrefix=1
        - id: bytefinger-job
          uri: lb://bytefinger-job
          predicates:
            - Path=/job/**
          filters:
            - StripPrefix=1
        - id: bytefinger-report
          uri: lb://bytefinger-report
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
