# --- roles/nacos/tasks/main.yml ---
# 負責執行 Nacos 的設定腳本。

- name: Run Nacos setup script
  ansible.builtin.command:
    cmd: ./setup-nacos.sh
    chdir: "{{ scripts_dest_path }}"
    creates: /opt/auditsystem/nacos-server/bin/startup.sh
  args:
    creates: /opt/auditsystem/nacos-server/bin/startup.sh