# Business Service Configuration
# Data ID: bytefinger-biz
# Group: bytefinger-audit-local
# Namespace: public

server:
  port: 8500

spring:
  application:
    name: bytefinger-biz
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: 
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace:
        group: bytefinger-audit-local
        file-extension: yml

# Department configuration (from existing nacos config)
user:
  deptName: 运营管理部

# Download configuration (specific to biz service)
downLoad:
  host: http://localhost:8400

# OA configuration (fixes missing oa.dataBoardUrl property)
oa:
  dataBoardUrl: http://localhost:8400/api/dashboard

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
